name: smtmonitoring
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.4.0
  flutter_svg: ^2.0.9
  provider: ^6.1.1
  shared_preferences: ^2.3.1
  connectivity_plus: ^6.0.5
  flutter_svg_provider : ^1.0.7
  flutter_test:
    sdk: flutter
  flutter_switch: ^0.3.2
dependency_overrides:
  collection: ^1.19.0
  http_parser: ^4.1.0
  material_color_utilities: ^0.12.0
  meta: ^1.15.0
  string_scanner: ^1.3.0   
dev dependencies:
  flutter test:
    sdk: flutter
  flutter_lints: ^3.0.0   
flutter: 
  uses-material-design: true 
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Poppins 
      fonts:
        - asset: assets/fonts/PoppinsSemiBold.ttf 
          weight: 600
        - asset: assets/fonts/PoppinsMedium.ttf 
          weight: 500
        - asset: assets/fonts/PoppinsRegular.ttf 
          weight: 400
        - asset: assets/fonts/PoppinsBold.ttf 
          weight: 700
        - asset: assets/fonts/PoppinsLight.ttf 
          weight: 300
    - family: League Spartan
      fonts:
        - asset: assets/fonts/LeagueSpartanRegular.ttf 
          weight: 400
        - asset: assets/fonts/LeagueSpartanSemiBold.ttf   
          weight: 600
        - asset: assets/fonts/LeagueSpartanLight.ttf 
          weight: 300
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSansRegular.ttf 
          weight: 400
        - asset: assets/fonts/NunitoSansBold.ttf 
          weight: 700
        - asset: assets/fonts/NunitoSansExtraBold.ttf 
          weight: 800
    - family: Inter
      fonts:
        - asset: assets/fonts/InterBold.ttf
          weight: 700
    - family: PT Serif 
      fonts:
         - asset: assets/fonts/PTSerifRegular.ttf
           weight: 400
         - asset: assets/fonts/PTSerifBold.ttf 
           weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoLight.ttf 
          weight: 300
        - asset: assets/fonts/RobotoRomanRegular.ttf 
          weight: 400
        - asset: assets/fonts/RobotoRomanLight.ttf 
          weight: 300
    - family: Work Sans
      fonts:
        - asset: assets/fonts/WorkSansRegular.ttf 
          weight: 400
  
